import { StyleSheet } from 'react-native';

import { Spacing, Radii, Components, Typography } from '@/constants/theme';

export const styles = StyleSheet.create({
  quickRow: { justifyContent: 'space-between', gap: Spacing.xs },
  quickItem: { alignItems: 'center', gap: Spacing.xxs, flex: 1 },
  quickIcon: { width: 44, height: 44, borderRadius: Radii.xl, alignItems: 'center', justifyContent: 'center' },
  quickLabel: { ...Typography.caption },
  sectionCard: { gap: Spacing.sm, padding: Spacing.sm },
  sectionHeaderRow: { alignItems: 'center', justifyContent: 'space-between', gap: Spacing.sm },
  sectionTitle: { ...Typography.subheading },
  sectionHint: { ...Typography.caption },
  completionCard: { borderLeftWidth: 3 },
  completionHeader: { alignItems: 'center', gap: Spacing.sm },
  completionIcon: { width: 36, height: 36, borderRadius: Radii.xl, alignItems: 'center', justifyContent: 'center' },
  completionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing.sm,
    borderRadius: Radii.sm,
    borderWidth: 1,
    gap: Spacing.sm,
  },
  completionRowContent: { flex: 1, gap: Spacing.micro },
  completionRowTitle: { ...Typography.bodySmall, letterSpacing: -0.1 },
  completionRowMeta: { ...Typography.caption },
  completionActionChip: {
    borderRadius: Radii.pill,
    paddingHorizontal: Spacing.xs,
    paddingVertical: Spacing.xxs,
  },
  completionActionText: {
    ...Typography.caption,
    fontWeight: '700',
  },
  completionHint: { ...Typography.caption, textAlign: 'center' },
  attentionList: { gap: Spacing.xs },
  rowCard: { padding: Spacing.sm, borderRadius: Radii.card, borderWidth: 1, gap: Spacing.sm, alignItems: 'stretch' },
  rowTop: { alignItems: 'center', gap: Spacing.sm },
  rowLeft: { flex: 1, minWidth: 0, alignItems: 'center', gap: Spacing.sm },
  rowContent: { flex: 1, gap: Spacing.micro },
  actionRow: { flexWrap: 'wrap', gap: Spacing.xxs },
  pill: { alignItems: 'center', gap: Spacing.xxs, paddingHorizontal: Spacing.xs, paddingVertical: Spacing.xxs, borderRadius: Radii.pill },
  pillLabel: { ...Typography.caption, letterSpacing: -0.1 },
  actionPill: { alignItems: 'center', gap: Spacing.xs, paddingHorizontal: Spacing.md, paddingVertical: Spacing.xs, borderRadius: Radii.md, borderWidth: 1 },
  subtleMeta: { ...Typography.caption },
  avatar: { width: Components.avatar.md, height: Components.avatar.md, borderRadius: Components.avatar.md / 2, alignItems: 'center', justifyContent: 'center', position: 'relative', overflow: 'visible' },
  avatarText: { ...Typography.heading },
  badge: { position: 'absolute', top: -2, right: -2, width: 12, height: 12, borderRadius: Radii.sm, borderWidth: 2 },
  athleteName: { ...Typography.bodySemiBold, letterSpacing: -0.1 },
  athleteMetadata: { ...Typography.small },
  recentRow: { padding: Spacing.sm, borderRadius: Radii.card, borderWidth: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.sm },
  emptyStateInline: { alignItems: 'center', gap: Spacing.sm, paddingVertical: Spacing.xs, paddingHorizontal: Spacing.xs },
  emptyCopy: { flex: 1, gap: Spacing.micro },
  emptyIconCircle: { width: 44, height: 44, borderRadius: Radii.pill, alignItems: 'center', justifyContent: 'center' },
  emptyText: { ...Typography.bodySmall },
  badgesShortcut: { alignItems: 'center', gap: Spacing.sm, padding: Spacing.md, borderRadius: Radii.card, borderWidth: 1 },
  badgesIcon: { width: 40, height: 40, borderRadius: Radii.xl, alignItems: 'center', justifyContent: 'center' },
});
