import { StyleSheet } from 'react-native';

import { Radii, Spacing, Typography } from '@/constants/theme';

export const styles = StyleSheet.create({
  choiceContainer: { gap: Spacing.md },
  choiceSubtitle: { ...Typography.body, marginBottom: Spacing.sm },
  choiceCard: {
    alignItems: 'center',
    padding: Spacing.md,
    borderRadius: Radii.lg,
    borderWidth: 2,
    gap: Spacing.md,
  },
  choiceIcon: {
    width: 56,
    height: 56,
    borderRadius: Radii['2xl'],
    alignItems: 'center',
    justifyContent: 'center',
  },
  choiceInfo: { flex: 1, gap: Spacing.xxs },
  choiceTitle: { ...Typography.subheading },
  choiceDesc: { ...Typography.small, lineHeight: Typography.caption.lineHeight },
  sessionList: { gap: Spacing.sm },
  sectionSubtitle: { ...Typography.bodySmall, marginBottom: Spacing.sm },
  sessionCard: {
    alignItems: 'center',
    padding: Spacing.md,
    borderRadius: Radii.md,
    borderWidth: 1,
    gap: Spacing.md,
  },
  sessionDate: {
    alignItems: 'center',
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    borderRadius: Radii.sm,
    minWidth: 50,
  },
  sessionDayName: { ...Typography.micro, textTransform: 'uppercase' },
  sessionDateStr: { ...Typography.caption },
  sessionInfo: { flex: 1, gap: Spacing.xxs },
  sessionMeta: { alignItems: 'center', gap: Spacing.xxs },
  sessionMetaText: { ...Typography.caption },
  spotsBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: Spacing.xs,
    paddingVertical: Spacing.micro,
    borderRadius: Radii.sm,
    marginTop: Spacing.xxs,
  },
  emptyState: { alignItems: 'center', paddingVertical: Spacing['2xl'], gap: Spacing.sm },
  emptyText: { ...Typography.body },
  createButton: {
    alignItems: 'center',
    gap: Spacing.xxs,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderRadius: Radii.md,
    marginTop: Spacing.md,
  },
  createButtonText: { fontWeight: '600' },
  confirmContainer: { gap: Spacing.md },
  confirmCard: { padding: Spacing.lg, gap: Spacing.md },
  confirmHeader: { alignItems: 'center' },
  confirmDetail: { gap: Spacing.xxs },
  confirmLabel: { ...Typography.caption, textTransform: 'uppercase', fontWeight: '600' },
  confirmButton: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.xs,
    paddingVertical: Spacing.md,
    borderRadius: Radii.md,
  },
  confirmButtonText: { ...Typography.subheading },
  changeButton: {
    alignItems: 'center',
    paddingVertical: Spacing.md,
    borderRadius: Radii.md,
    borderWidth: 1,
  },
});
