export const BOOKING_LOCATION_OPTIONS = {
  COACH_PRESET: 'Coach preset venue',
  MY_LOCATION: 'My location',
  NEUTRAL_VENUE: 'Neutral venue',
  VIRTUAL: 'Virtual session',
} as const;

export const BOOKING_LOCATION_OPTION_LIST = [
  BOOKING_LOCATION_OPTIONS.COACH_PRESET,
  BOOKING_LOCATION_OPTIONS.MY_LOCATION,
  BOOKING_LOCATION_OPTIONS.NEUTRAL_VENUE,
  BOOKING_LOCATION_OPTIONS.VIRTUAL,
] as const;
