import {
  AthleteObjective,
  BookingSummary,
  ChatMessage,
  ChatThreadSummary,
  CoachProfile,
  PaymentReminder,
  SessionHistoryEntry,
  School,
  InviteCode,
  CoachReview,
  UserProfile,
  CoachFeedback,
  SkillLevel,
} from './types';

const coachPhotos = [
  'https://images.unsplash.com/photo-1544717302-de2939b7ef71?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1521412644187-c49fa049e84d?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1508174432729-1d8663b438c1?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1521412644187-c49fa049e84d?auto=format&fit=crop&w=800&q=80',
];

const coverPhotos = [
  'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1551958219-acbc608c6377?auto=format&fit=crop&w=1200&q=80',
];

// Schools
export const schools: School[] = [
  {
    id: 'school-1',
    name: "Maya's High Press Lab",
    address: '123 Football Drive',
    city: 'Austin',
    state: 'TX',
    zipCode: '78701',
    photoUrl: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?auto=format&fit=crop&w=800&q=80',
    description: 'Elite football training facility focused on attacking play and technical development.',
    activeCoachesCount: 8,
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'school-2',
    name: 'North Texas Shield Collective',
    address: '456 Defense Boulevard',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75201',
    photoUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=800&q=80',
    description: 'Defensive excellence and tactical awareness training center.',
    activeCoachesCount: 12,
    createdAt: '2024-01-10T00:00:00Z',
  },
  {
    id: 'school-3',
    name: "Cam's Safe Hands Lab",
    address: '789 Goalkeeper Way',
    city: 'Houston',
    state: 'TX',
    zipCode: '77002',
    photoUrl: 'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?auto=format&fit=crop&w=800&q=80',
    description: 'Premier goalkeeper academy with state-of-the-art training equipment.',
    activeCoachesCount: 5,
    createdAt: '2024-01-20T00:00:00Z',
  },
];

// Invite Codes
export const inviteCodes: InviteCode[] = [
  {
    id: 'invite-1',
    code: 'HIGHPRESS2024',
    schoolId: 'school-1',
    schoolName: "Maya's High Press Lab",
    createdBy: 'admin-1',
    createdAt: '2024-03-01T00:00:00Z',
    expiresAt: '2024-12-31T23:59:59Z',
    maxUses: 20,
    currentUses: 8,
    status: 'active',
  },
  {
    id: 'invite-2',
    code: 'SHIELD2024',
    schoolId: 'school-2',
    schoolName: 'North Texas Shield Collective',
    createdBy: 'admin-1',
    createdAt: '2024-03-01T00:00:00Z',
    expiresAt: '2024-12-31T23:59:59Z',
    maxUses: 30,
    currentUses: 12,
    status: 'active',
  },
  {
    id: 'invite-3',
    code: 'SAFEHANDS2024',
    schoolId: 'school-3',
    schoolName: "Cam's Safe Hands Lab",
    createdBy: 'admin-1',
    createdAt: '2024-03-01T00:00:00Z',
    expiresAt: '2024-12-31T23:59:59Z',
    maxUses: 15,
    currentUses: 5,
    status: 'active',
  },
];

export const coachProfiles: CoachProfile[] = [
  {
    id: 'coach-1',
    fullName: 'Maya Ellis',
    primarySport: 'Football',
    sports: ['Football'],
    city: 'Austin',
    state: 'TX',
    distanceMiles: 4.2,
    rating: { average: 4.9, reviewCount: 86 },
    priceRange: { minUsd: 90, maxUsd: 140, unitLabel: 'session' },
    nextAvailability: '2024-03-16T15:00:00Z',
    badges: [
      { id: 'verified', label: 'Background check', tone: 'success' },
      { id: 'pro', label: 'Pro experience' },
    ],
    sessionFormats: ['In-person', 'Small group'],
    shortBio:
      'UEFA B coach building first-touch confidence for wingers and attacking mids with film + GPS data.',
    profilePhotoUrl: coachPhotos[0],
    coverPhotoUrl: coverPhotos[0],
    schoolName: "Maya's High Press Lab",
    schoolId: 'school-1',
    footballFocuses: ['Dribbling', 'Finishing', 'Passing'],
    location: { lat: 30.27, lng: -97.74 },
    bio: 'Passionate football coach with 10+ years of experience developing young athletes. I specialize in attacking play, technical skills, and building player confidence. My coaching philosophy centers on creating a positive, challenging environment where players can unlock their full potential through structured training, video analysis, and personalized feedback.',
    phone: '+1 (512) 555-0123',
    email: 'maya@highpresslab.com',
    website: 'https://highpresslab.com',
    joinedDate: '2024-01-15T00:00:00Z',
    totalSessions: 342,
    languages: ['English', 'Spanish'],
    achievements: [
      'UEFA B Licensed Coach',
      '5x Regional Coach of the Year',
      'Developed 12 players to collegiate level',
      '100+ 5-star reviews',
    ],
    experiences: [
      {
        id: 'exp-1',
        title: 'Head Coach',
        organization: "Maya's High Press Lab",
        startDate: '2024-01-15T00:00:00Z',
        current: true,
        description: 'Founded and lead elite football training facility focused on technical development.',
      },
      {
        id: 'exp-2',
        title: 'Technical Director',
        organization: 'Austin Youth Soccer Academy',
        startDate: '2020-06-01T00:00:00Z',
        endDate: '2024-01-01T00:00:00Z',
        current: false,
        description: 'Developed curriculum and coached competitive youth teams ages 12-18.',
      },
      {
        id: 'exp-3',
        title: 'Professional Player',
        organization: 'NWSL - Portland Thorns',
        startDate: '2016-01-01T00:00:00Z',
        endDate: '2019-12-31T00:00:00Z',
        current: false,
        description: 'Midfielder/Forward - 3 seasons professional experience.',
      },
    ],
    certifications: [
      {
        id: 'cert-1',
        name: 'UEFA B Coaching License',
        issuer: 'UEFA',
        issueDate: '2020-08-15T00:00:00Z',
      },
      {
        id: 'cert-2',
        name: 'USSF National C License',
        issuer: 'US Soccer Federation',
        issueDate: '2019-03-20T00:00:00Z',
      },
      {
        id: 'cert-3',
        name: 'SafeSport Certified',
        issuer: 'U.S. Center for SafeSport',
        issueDate: '2024-01-01T00:00:00Z',
        expiryDate: '2025-01-01T00:00:00Z',
      },
    ],
    posts: [
      {
        id: 'post-1',
        coachId: 'coach-1',
        content: 'Incredible session with the U14 squad today! Working on quick combination play and finishing under pressure. So proud of the progress! 🔥⚽',
        mediaUrls: [
          'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1606925797300-0b35e9d1794e?auto=format&fit=crop&w=800&q=80',
        ],
        mediaType: 'photo',
        createdAt: '2024-03-14T18:30:00Z',
        likes: 42,
        comments: 8,
      },
      {
        id: 'post-2',
        coachId: 'coach-1',
        content: 'New training video series dropping soon! Breaking down 1v1 attacking moves that actually work in game situations. Stay tuned! 🎥',
        createdAt: '2024-03-12T10:15:00Z',
        likes: 67,
        comments: 15,
      },
    ],
    photoGallery: [
      'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1606925797300-0b35e9d1794e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=800&q=80',
    ],
    videoGallery: [],
  },
  {
    id: 'coach-2',
    fullName: 'Jordan Vega',
    primarySport: 'Football',
    sports: ['Football'],
    city: 'Dallas',
    state: 'TX',
    distanceMiles: 9.8,
    rating: { average: 4.8, reviewCount: 56 },
    priceRange: { minUsd: 95, maxUsd: 135, unitLabel: 'session' },
    nextAvailability: '2024-03-16T17:30:00Z',
    badges: [
      { id: 'verified', label: 'Background check', tone: 'success' },
      { id: 'ncaa', label: 'NWSL Cup', tone: 'default' },
    ],
    sessionFormats: ['In-person', 'Virtual'],
    shortBio:
      'Former NWSL outside back specializing in defensive IQ, pressing triggers, and transition defending.',
    profilePhotoUrl: coachPhotos[1],
    coverPhotoUrl: coverPhotos[1],
    schoolName: 'North Texas Shield Collective',
    schoolId: 'school-2',
    footballFocuses: ['Defending', 'Passing', 'Conditioning'],
    location: { lat: 32.78, lng: -96.8 },
    bio: 'Former professional defender turned coach. I help players master the art of defending through tactical awareness, positioning, and reading the game. My training combines modern defensive concepts with traditional fundamentals.',
    phone: '+1 (214) 555-0456',
    email: 'jordan@shieldcollective.com',
    website: 'https://shieldcollective.com',
    joinedDate: '2024-01-10T00:00:00Z',
    totalSessions: 256,
    languages: ['English'],
    achievements: ['NWSL Championship Winner', 'All-Star Selection 2x', '50+ players to competitive teams'],
    experiences: [
      {
        id: 'exp-4',
        title: 'Defensive Coach',
        organization: 'North Texas Shield Collective',
        startDate: '2024-01-10T00:00:00Z',
        current: true,
      },
      {
        id: 'exp-5',
        title: 'Professional Player',
        organization: 'NWSL - FC Dallas',
        startDate: '2018-01-01T00:00:00Z',
        endDate: '2023-12-31T00:00:00Z',
        current: false,
      },
    ],
    certifications: [
      {
        id: 'cert-4',
        name: 'USSF B License',
        issuer: 'US Soccer Federation',
        issueDate: '2023-06-15T00:00:00Z',
      },
    ],
    posts: [],
    photoGallery: [],
    videoGallery: [],
  },
  {
    id: 'coach-3',
    fullName: 'Cam Winters',
    primarySport: 'Football',
    sports: ['Football'],
    city: 'Houston',
    state: 'TX',
    distanceMiles: 11.1,
    rating: { average: 5.0, reviewCount: 42 },
    priceRange: { minUsd: 110, maxUsd: 180, unitLabel: 'session' },
    nextAvailability: '2024-03-17T20:00:00Z',
    badges: [{ id: 'verified', label: 'Background check', tone: 'success' }],
    sessionFormats: ['In-person'],
    shortBio:
      'Goalkeeper academy director layering reaction drills with neuro training and off-season conditioning.',
    profilePhotoUrl: coachPhotos[2],
    coverPhotoUrl: coverPhotos[2],
    schoolName: "Cam's Safe Hands Lab",
    schoolId: 'school-3',
    footballFocuses: ['Goalkeeping', 'Conditioning', 'Passing'],
    location: { lat: 29.76, lng: -95.36 },
    bio: 'Elite goalkeeper coach specializing in reaction training, positioning, and mental preparation. I use cutting-edge technology and proven methods to develop confident, commanding goalkeepers.',
    phone: '+1 (713) 555-0789',
    email: 'cam@safehandslab.com',
    website: 'https://safehandslab.com',
    joinedDate: '2024-01-20T00:00:00Z',
    totalSessions: 189,
    languages: ['English', 'Portuguese'],
    achievements: ['Goalkeeper Coach of the Year 2023', '15+ goalkeepers to collegiate programs', 'International coaching certification'],
    experiences: [
      {
        id: 'exp-6',
        title: 'Academy Director',
        organization: "Cam's Safe Hands Lab",
        startDate: '2024-01-20T00:00:00Z',
        current: true,
      },
    ],
    certifications: [
      {
        id: 'cert-5',
        name: 'Goalkeeper Specialist License',
        issuer: 'USSF',
        issueDate: '2022-09-01T00:00:00Z',
      },
    ],
    posts: [],
    photoGallery: [],
    videoGallery: [],
  },
];

export const upcomingBookings: BookingSummary[] = [
  {
    id: 'booking-1',
    coachName: 'Maya Ellis',
    childName: 'Eli',
    service: 'Elite Finishing Session',
    start: '2024-03-18T15:30:00Z',
    status: 'Confirmed',
    locationLabel: 'Austin Sports Academy',
  },
  {
    id: 'booking-2',
    coachName: 'Jordan Vega',
    childName: 'Ivy',
    service: 'Ball-Handling Intensive',
    start: '2024-03-21T00:30:00Z',
    status: 'Pending',
    locationLabel: 'Dallas Elite Gym',
  },
];

export const chatThreads: ChatThreadSummary[] = [
  {
    id: 'chat-thread-1',
    bookingId: 'booking-1',
    coachName: 'Maya Ellis',
    childName: 'Eli',
    serviceName: 'Elite Finishing Session',
    location: 'Austin Sports Academy · Pitch 2',
    scheduledFor: '2024-03-18T15:30:00Z',
    unreadCount: 2,
    safetyCopy: 'Chats unlock once a booking is confirmed. Moderation + read receipts keep families protected.',
    pinnedObjectives: ['Dribbling', 'Finishing'],
  },
  {
    id: 'chat-thread-2',
    bookingId: 'booking-2',
    coachName: 'Jordan Vega',
    childName: 'Eli',
    serviceName: 'Passing Masterclass',
    location: 'Dallas FC Complex',
    scheduledFor: '2024-03-20T10:00:00Z',
    unreadCount: 0,
    safetyCopy: '',
    pinnedObjectives: ['Passing'],
  },
  {
    id: 'chat-thread-3',
    bookingId: 'booking-3',
    coachName: 'Alex Chen',
    childName: 'Eli',
    serviceName: 'GK Positioning Clinic',
    location: 'Elite Sports Park',
    scheduledFor: '2024-03-22T16:00:00Z',
    unreadCount: 1,
    safetyCopy: '',
    pinnedObjectives: ['Goalkeeping'],
  },
];

export const primaryChatThread: ChatThreadSummary = chatThreads[0];

export const chatMessages: ChatMessage[] = [
  {
    id: 'msg-1',
    sender: 'coach',
    body: 'Hey team! Pumped to work with Eli again. Drop any updates from the last match?',
    createdAt: '2024-03-15T14:02:00Z',
    status: 'seen',
  },
  {
    id: 'msg-2',
    sender: 'parent',
    body: 'He’s still buzzing from districts. We want to sharpen first-touch + composure under pressure.',
    createdAt: '2024-03-15T14:05:00Z',
    status: 'seen',
  },
  {
    id: 'msg-3',
    sender: 'coach',
    body: 'Love it. I’ll set up a rondo ladder + finishing gauntlet. Sharing the prep doc now.',
    createdAt: '2024-03-15T14:08:00Z',
    status: 'seen',
    attachments: [
      {
        id: 'att-1',
        type: 'pdf',
        title: 'Session blueprint · Match sharpness',
        subtitle: 'PDF · 2.1 MB',
      },
    ],
  },
  {
    id: 'msg-4',
    sender: 'parent',
    body: 'Legend. Eli will hydrate + arrive 15 early. Need anything signed ahead of time?',
    createdAt: '2024-03-15T14:10:00Z',
    status: 'seen',
  },
  {
    id: 'msg-5',
    sender: 'coach',
    body: 'All set. I’ll push footage + progress tags here after the session so you can log it in the performance hub.',
    createdAt: '2024-03-15T14:11:00Z',
    status: 'delivered',
  },
  {
    id: 'msg-6',
    sender: 'parent',
    body: 'Perfect—thanks Maya!',
    createdAt: '2024-03-15T14:11:45Z',
    status: 'sent',
  },
];

export const activeObjectives: AthleteObjective[] = [
  {
    id: 'obj-1',
    label: 'Dribbling',
    status: 'active',
    updatedAt: '2024-03-14T16:00:00Z',
    note: 'Beat defenders 1v1 on the wing',
    coachName: 'Maya Ellis',
    progress: 65,
    sessionsCompleted: 8,
    startDate: '2024-01-15T00:00:00Z',
    targetSessions: 12,
  },
  {
    id: 'obj-2',
    label: 'Passing',
    status: 'active',
    updatedAt: '2024-03-12T16:00:00Z',
    note: 'Switch the field under pressure',
    coachName: 'Jordan Vega',
    progress: 45,
    sessionsCompleted: 5,
    startDate: '2024-02-01T00:00:00Z',
    targetSessions: 10,
  },
  {
    id: 'obj-3',
    label: 'Defending',
    status: 'upcoming',
    updatedAt: '2024-03-10T16:00:00Z',
    note: 'Body shape when jockeying',
    coachName: 'Jordan Vega',
    progress: 0,
    sessionsCompleted: 0,
    startDate: '2024-03-20T00:00:00Z',
  },
];

export const sessionHistory: SessionHistoryEntry[] = [
  {
    id: 'session-1',
    date: '2024-03-11T15:30:00Z',
    coachName: 'Maya Ellis',
    focus: 'Finishing',
    location: 'Austin Sports Academy · Pitch 2',
    highlight: 'Tied finishing gauntlet personal best (8/10).',
    resultBadge: 'Hat-trick ready',
    clipLabel: 'Finishing drill clips',
    durationMinutes: 60,
    sessionType: '1-on-1',
    dateCompleted: '2024-03-11T16:30:00Z',
    rating: 5,
    coachFeedback: 'Exceptional focus today. Shot accuracy improving consistently.',
  },
  {
    id: 'session-2',
    date: '2024-03-04T15:30:00Z',
    coachName: 'Jordan Vega',
    focus: 'Defending',
    location: 'North Texas Shield Collective',
    highlight: 'Mastered 1v1 delay + angled pressing cues.',
    durationMinutes: 90,
    sessionType: 'Small group',
    dateCompleted: '2024-03-04T17:00:00Z',
    rating: 5,
    coachFeedback: 'Great positioning. Keep working on reaction speed.',
  },
  {
    id: 'session-3',
    date: '2024-02-26T15:30:00Z',
    coachName: 'Cam Winters',
    focus: 'Conditioning',
    location: "Cam's Safe Hands Lab",
    highlight: 'VO2 drills logged, recovery HR down 8 bpm.',
    durationMinutes: 75,
    sessionType: '1-on-1',
    dateCompleted: '2024-02-26T16:45:00Z',
    rating: 4,
    coachFeedback: 'Strong improvement in stamina. Maintain the intensity.',
  },
];

export const paymentReminders: PaymentReminder[] = [
  {
    id: 'payment-1',
    title: '4-pack of finishing sessions',
    amountUsd: 520,
    dueDate: '2024-03-20T15:00:00Z',
    status: 'pending',
    description: 'Auto-captures after the March 18th session unless cancelled 24h prior.',
  },
  {
    id: 'payment-2',
    title: 'Cam's Safe Hands Lab drop-in',
    amountUsd: 150,
    dueDate: '2024-03-24T18:00:00Z',
    status: 'placeholder',
    description: 'Stripe Connect onboarding gated, but the slot is reserved.',
  },
  {
    id: 'payment-3',
    title: 'Shield Collective defensive clinic',
    amountUsd: 260,
    dueDate: '2024-03-12T15:00:00Z',
    status: 'paid',
    description: 'Captured with card ending in ··42. Receipt emailed.',
  },
];

export const mockUserProfile: UserProfile = {
  id: 'user-1',
  fullName: 'Sarah Johnson',
  email: 'sarah.johnson@example.com',
  phone: '+1 (512) 555-9876',
  profilePhotoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=400&q=80',
  bio: 'Parent of two young athletes passionate about football development',
  role: 'Parent',
  joinedDate: '2024-01-05T00:00:00Z',
  children: [
    { name: 'Eli', age: 14 },
    { name: 'Ivy', age: 12 },
  ],
};

export const coachFeedbackHistory: CoachFeedback[] = [
  {
    id: 'feedback-1',
    sessionId: 'session-1',
    coachId: 'coach-1',
    athleteId: 'user-1',
    rating: 5,
    notes: 'Exceptional focus today. Shot accuracy improving consistently. Eli is showing great composure in finishing situations.',
    highlights: ['8/10 on finishing gauntlet', 'Improved weak foot accuracy', 'Great decision-making in box'],
    areasToImprove: ['First touch consistency', 'Movement off the ball'],
    skillsWorked: ['Finishing', 'Dribbling'],
    skillUpdates: [
      { skill: 'Finishing', previousLevel: 60, newLevel: 68 },
      { skill: 'Dribbling', previousLevel: 62, newLevel: 65 },
    ],
    createdAt: '2024-03-11T16:30:00Z',
  },
  {
    id: 'feedback-2',
    sessionId: 'session-2',
    coachId: 'coach-2',
    athleteId: 'user-1',
    rating: 5,
    notes: 'Great positioning work today. Keep working on reaction speed in 1v1 situations.',
    highlights: ['Excellent body positioning', 'Quick recovery runs', 'Reading attacker movements'],
    areasToImprove: ['Reaction speed', 'Communication with teammates'],
    skillsWorked: ['Defending'],
    skillUpdates: [
      { skill: 'Defending', previousLevel: 40, newLevel: 48 },
    ],
    createdAt: '2024-03-04T17:00:00Z',
  },
];

export const athleteSkillLevels: SkillLevel[] = [
  { skill: 'Dribbling', level: 65, lastUpdated: '2024-03-11T16:30:00Z' },
  { skill: 'Passing', level: 55, lastUpdated: '2024-03-04T17:00:00Z' },
  { skill: 'Defending', level: 48, lastUpdated: '2024-03-04T17:00:00Z' },
  { skill: 'Finishing', level: 68, lastUpdated: '2024-03-11T16:30:00Z' },
  { skill: 'Goalkeeping', level: 30, lastUpdated: '2024-02-15T00:00:00Z' },
  { skill: 'Conditioning', level: 52, lastUpdated: '2024-02-26T16:45:00Z' },
];
