import { StyleSheet } from 'react-native';

import { Radii, Spacing } from '@/constants/theme';
import { scaleFont } from '@/utils/scale';

export const styles = StyleSheet.create({
  compactCard: {
    alignItems: 'center',
    padding: Spacing.sm,
    marginBottom: Spacing.sm,
    gap: Spacing.sm,
  },
  iconContainer: {
    width: 44,
    height: 44,
    borderRadius: Radii.xl,
    alignItems: 'center',
    justifyContent: 'center',
  },
  compactContent: { flex: 1, gap: Spacing.xxs },
  compactHeader: {
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.xs,
  },
  compactTitle: { flex: 1, fontSize: scaleFont(15) },
  statusPill: {
    paddingHorizontal: 8,
    paddingVertical: Spacing.micro,
    borderRadius: Radii.sm,
  },
  statusText: { fontSize: scaleFont(11), fontWeight: '600' },
  compactDetails: { gap: Spacing.md },
  detailItem: { alignItems: 'center', gap: Spacing.xxs },
  detailText: { fontSize: scaleFont(12) },
  header: { alignItems: 'center', gap: Spacing.sm },
  avatarLarge: {
    width: 48,
    height: 48,
    borderRadius: Radii.xl,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerInfo: { flex: 1, gap: Spacing.micro },
  title: { fontSize: scaleFont(17), fontWeight: '700', letterSpacing: -0.2 },
  driverName: { fontSize: scaleFont(13) },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: Radii.sm },
  statusBadgeText: { fontSize: scaleFont(12), fontWeight: '600' },
  detailsContainer: { gap: Spacing.xs, marginTop: Spacing.xs },
  detailRow: { alignItems: 'flex-start', gap: Spacing.xs },
  detailLabel: { flex: 1, fontSize: scaleFont(14), lineHeight: scaleFont(20) },
  seatsSection: {
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: Spacing.sm,
    borderTopWidth: 1,
    marginTop: Spacing.xs,
  },
  seatsInfo: { alignItems: 'center', gap: Spacing.xxs },
  seatsText: { fontSize: scaleFont(14), fontWeight: '500' },
  pendingBadge: { paddingHorizontal: 8, paddingVertical: Spacing.xxs, borderRadius: Radii.sm },
  pendingText: { fontSize: scaleFont(12), fontWeight: '600' },
  actions: { marginTop: Spacing.xs },
  actionButton: { width: '100%' },
  buttonContent: { alignItems: 'center', gap: 8 },
  buttonText: { fontWeight: '600', fontSize: scaleFont(15) },
  confirmedBanner: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: Spacing.sm,
    borderRadius: Radii.md,
  },
  confirmedText: { fontWeight: '600', fontSize: scaleFont(14) },
  pendingBanner: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: Spacing.sm,
    borderRadius: Radii.md,
  },
  pendingBannerText: { fontWeight: '600', fontSize: scaleFont(14) },
});
