import type { CoachCardData } from '@/components/coach';

export const MIN_FEATURED_RATING = 4.5;

export const MOCK_FEATURED_COACHES: CoachCardData[] = [
  {
    id: 'f1',
    fullName: 'Emma Richardson',
    profilePhotoUrl: 'https://i.pravatar.cc/150?u=featured1',
    verified: true,
    rating: 4.9,
    reviewCount: 142,
    distanceMiles: 0.8,
    pricePerHour: 40,
    specialties: ['Passing', 'Tactical'],
    reviewQuote: 'Incredibly structured sessions with visible results.',
    reviewAuthor: 'Tom B.',
    nextAvailable: 'Tomorrow, 4 PM',
    trialAvailable: true,
  },
  {
    id: 'f2',
    fullName: 'Liam Johnson',
    profilePhotoUrl: 'https://i.pravatar.cc/150?u=featured2',
    verified: true,
    rating: 4.8,
    reviewCount: 98,
    distanceMiles: 1.5,
    pricePerHour: 35,
    specialties: ['Dribbling', 'Finishing'],
    reviewQuote: 'My son improved massively in just 3 weeks.',
    reviewAuthor: 'Kate M.',
    nextAvailable: 'Sat, 10 AM',
    trialAvailable: false,
  },
  {
    id: 'f3',
    fullName: 'Sofia Patel',
    profilePhotoUrl: 'https://i.pravatar.cc/150?u=featured3',
    verified: true,
    rating: 5.0,
    reviewCount: 67,
    distanceMiles: 2.1,
    pricePerHour: 50,
    specialties: ['Goalkeeping', 'Fitness'],
    nextAvailable: 'Today, 6 PM',
    trialAvailable: true,
  },
  {
    id: 'f4',
    fullName: 'Noah Williams',
    profilePhotoUrl: 'https://i.pravatar.cc/150?u=featured4',
    verified: true,
    rating: 4.7,
    reviewCount: 83,
    distanceMiles: 3.0,
    pricePerHour: 30,
    specialties: ['Defending', 'Conditioning'],
    nextAvailable: 'Mon, 5 PM',
    trialAvailable: true,
  },
];
